import React, {useCallback, useEffect, useState} from 'react';
import {Alert, AppState, DeviceEventEmitter, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {en} from './src/strings/en';
import {ur} from './src/strings/ur';
import {PlannerMode, StepliOverlay} from './src/native/StepliOverlay';

type Language = 'en' | 'ur';
type RootStack = {Language: undefined; Permissions: undefined; Onboarding: {page: number}; Home: undefined; Settings: undefined};
const Stack = createNativeStackNavigator<RootStack>();
const C = {cream: '#A8C3A0', sage: '#6E8B72', dark: '#284435', amber: '#C86D45', ink: '#26352B', pale: '#E5EDDC'};
const stepliLogo = require('./src/assets/stepli-bot.png');
const copyFor = (language: Language) => language === 'ur' ? ur : en;

function Button({label, onPress, secondary = false, rtl = false}: {label: string; onPress: () => void; secondary?: boolean; rtl?: boolean}) {
  return <Pressable accessibilityRole="button" style={[styles.button, secondary && styles.secondary]} onPress={onPress}><Text style={[styles.buttonText, secondary && styles.secondaryText, rtl && styles.rtl]}>{label}</Text></Pressable>;
}
function Screen({children, scroll = false}: {children: React.ReactNode; scroll?: boolean}) { const content = <View style={styles.screen}>{children}</View>; return <SafeAreaView style={styles.safe}>{scroll ? <ScrollView contentContainerStyle={styles.scroll}>{content}</ScrollView> : content}</SafeAreaView>; }
function CopyText({children, style, language}: {children: React.ReactNode; style?: object; language: Language}) { return <Text style={[style, language === 'ur' && styles.rtl]}>{children}</Text>; }

function LanguageScreen({onChoose}: {onChoose: (language: Language) => void}) {
  return <Screen><Image source={stepliLogo} style={styles.heroLogo}/><Text style={styles.eyebrow}>Stepli</Text><Text style={styles.title}>Choose your language</Text><Text style={[styles.title, styles.rtl]}>اپنی زبان منتخب کریں</Text><View style={styles.flex}/><Button label="English" onPress={() => onChoose('en')}/><Button label="اردو" rtl onPress={() => onChoose('ur')} secondary/></Screen>;
}
function Permissions({navigation, language}: any) {
  const c = copyFor(language); const [overlay, setOverlay] = useState(false); const [accessibility, setAccessibility] = useState(false);
  const refresh = useCallback(async () => { setOverlay(await StepliOverlay.canDrawOverlays()); setAccessibility(await StepliOverlay.isAccessibilityEnabled()); }, []);
  useEffect(() => { const unsubscribe = navigation.addListener('focus', refresh); const appState = AppState.addEventListener('change', state => { if (state === 'active') refresh(); }); refresh(); return () => { unsubscribe(); appState.remove(); }; }, [navigation, refresh]);
  useEffect(() => { if (overlay && accessibility) navigation.replace('Onboarding', {page: 1}); }, [overlay, accessibility, navigation]);
  const current = !overlay ? c.permissions.overlay : c.permissions.accessibility;
  return <Screen><CopyText language={language} style={styles.eyebrow}>{c.permissions.setup}</CopyText><CopyText language={language} style={styles.title}>{current.headline}</CopyText><CopyText language={language} style={styles.body}>{current.body}</CopyText>
    <View style={styles.permissionStatus}><CopyText language={language}>{overlay ? '✓' : '○'} {c.permissions.overlayStatus}</CopyText><CopyText language={language}>{accessibility ? '✓' : '○'} {c.permissions.accessibilityStatus}</CopyText></View>
    {overlay && !accessibility && <View style={styles.guide}><CopyText language={language} style={styles.guideTitle}>{c.permissions.guideTitle}</CopyText><CopyText language={language} style={styles.guideBody}>{c.permissions.guideBody}</CopyText></View>}
    <Button label={current.cta} rtl={language === 'ur'} onPress={() => !overlay ? StepliOverlay.openOverlaySettings() : StepliOverlay.openAccessibilitySettings()}/><Button secondary label={c.permissions.checkCta} rtl={language === 'ur'} onPress={refresh}/><CopyText language={language} style={styles.footnote}>{c.permissions.footnote}</CopyText>
  </Screen>;
}
function Onboarding({route, navigation, language, completeOnboarding}: any) { const c = copyFor(language); const page = route.params.page; const item = page === 1 ? c.onboarding.screen1 : c.onboarding.screen2; const finish = async () => { await completeOnboarding(); navigation.replace('Home'); }; return <Screen><CopyText language={language} style={styles.eyebrow}>{page} / 2</CopyText><CopyText language={language} style={styles.title}>{item.headline}</CopyText><CopyText language={language} style={styles.body}>{item.body}</CopyText><View style={styles.flex}/><Button rtl={language === 'ur'} label={page === 1 ? c.onboarding.continue : c.onboarding.begin} onPress={() => page === 1 ? navigation.push('Onboarding', {page: 2}) : finish()}/></Screen>; }
function Home({navigation, language}: any) {
  const c = copyFor(language); const [goal, setGoal] = useState(''); const [activeGoal, setActiveGoal] = useState<string | null>(null); const [lastInstruction, setLastInstruction] = useState<string | null>(null);
  useEffect(() => { StepliOverlay.getActiveGoal().then(value => { setActiveGoal(value); if (value) setGoal(value); }); const event = DeviceEventEmitter.addListener('stepliGuidanceUpdated', (raw: string) => { try { setLastInstruction(JSON.parse(raw).nextAction); } catch { setLastInstruction(null); } }); return () => event.remove(); }, []);
  const start = async (requestedGoal = goal, launchFoodpanda = false) => {
    if (!requestedGoal.trim()) { Alert.alert(language === 'ur' ? 'ایک مقصد لکھیں' : 'Add a goal', language === 'ur' ? 'بتائیں کہ آپ کیا کرنا چاہتے ہیں۔' : 'Tell Stepli what you want to do.'); return; }
    await StepliOverlay.startGuidance(requestedGoal); setGoal(requestedGoal); setActiveGoal(requestedGoal); setLastInstruction(null);
    if (launchFoodpanda) { const canOpen = await StepliOverlay.launchFoodpanda(); if (!canOpen) { await StepliOverlay.stopGuidance(); setActiveGoal(null); Alert.alert(c.common.notInstalledTitle, c.common.notInstalledBody); } }
  };
  const stop = async () => { await StepliOverlay.stopGuidance(); setActiveGoal(null); setLastInstruction(null); };
  const pizzaGoal = language === 'ur' ? 'فوڈ پانڈا سے پیزا آرڈر کریں' : 'Order pizza from Foodpanda';
  return <Screen scroll><View style={styles.topRow}><View style={styles.brand}><Image source={stepliLogo} style={styles.headerLogo}/><Text style={styles.logo}>Stepli</Text></View><Pressable accessibilityRole="button" onPress={() => navigation.navigate('Settings')}><CopyText language={language} style={styles.settings}>{c.home.settings}</CopyText></Pressable></View><CopyText language={language} style={styles.homeTitle}>{c.home.greeting}</CopyText><CopyText language={language} style={styles.body}>{c.home.subtext}</CopyText><CopyText language={language} style={styles.goalLabel}>{language === 'ur' ? 'آپ کا مقصد' : 'Your goal'}</CopyText><TextInput value={goal} onChangeText={setGoal} placeholder={language === 'ur' ? 'مثلاً کسی ریستوران سے پیزا آرڈر کریں' : 'For example, order a pizza'} placeholderTextColor="#657568" multiline style={[styles.goalInput, language === 'ur' && styles.rtl]} accessibilityLabel="Guidance goal"/><Button label={language === 'ur' ? 'رہنمائی شروع کریں' : 'Start guidance'} rtl={language === 'ur'} onPress={() => start()}/>{activeGoal && <View style={styles.activeGoal}><CopyText language={language} style={styles.activeGoalTitle}>{language === 'ur' ? 'رہنمائی جاری ہے' : 'Guidance is active'}</CopyText><CopyText language={language} style={styles.activeGoalText}>{activeGoal}</CopyText>{lastInstruction && <CopyText language={language} style={styles.lastInstruction}>{language === 'ur' ? 'اگلا قدم: ' : 'Next: '}{lastInstruction}</CopyText>}<Button secondary label={language === 'ur' ? 'رہنمائی روکیں' : 'Stop guidance'} rtl={language === 'ur'} onPress={stop}/></View>}<Pressable accessibilityRole="button" onPress={() => start(pizzaGoal, true)} style={styles.taskCard}><Text style={styles.cardIcon}>🍲</Text><View style={styles.flex}><CopyText language={language} style={styles.cardTitle}>{c.home.cardFoodpanda}</CopyText><CopyText language={language} style={styles.cardBody}>{language === 'ur' ? 'ایک مقصد مقرر کر کے فوڈ پانڈا کھولیں۔ اگلی ہدایت اسکرین سے طے ہوگی۔' : 'Set a goal and open Foodpanda. Every next step is decided from the screen.'}</CopyText></View><Text style={styles.arrow}>›</Text></Pressable></Screen>;
}
function Settings({language, setLanguage}: {language: Language; setLanguage: (value: Language) => void}) { const c = copyFor(language); const [voice, setVoice] = useState(true); const [large, setLarge] = useState(false); const [planner, setPlanner] = useState<PlannerMode>('local'); const [gptAvailable, setGptAvailable] = useState(false); useEffect(() => { Promise.all([StepliOverlay.getVoiceGuidance(), StepliOverlay.getPlannerMode(), StepliOverlay.isGptAvailable()]).then(([savedVoice, savedPlanner, available]) => { setVoice(savedVoice); setPlanner(savedPlanner); setGptAvailable(available); }); }, []); const updateVoice = async (enabled: boolean) => { setVoice(enabled); await StepliOverlay.setVoiceGuidance(enabled); }; const updatePlanner = async (mode: PlannerMode) => { setPlanner(mode); await StepliOverlay.setPlannerMode(mode); }; return <Screen scroll><CopyText language={language} style={styles.title}>{c.settings.title}</CopyText><CopyText language={language} style={styles.settingLabel}>{c.settings.language}</CopyText><Pressable style={styles.setting} onPress={() => setLanguage('en')}><Text>English</Text>{language === 'en' && <Text style={styles.active}>{c.settings.selected}</Text>}</Pressable><Pressable style={styles.setting} onPress={() => setLanguage('ur')}><CopyText language="ur">اردو</CopyText>{language === 'ur' && <CopyText language="ur" style={styles.active}>{c.settings.selected}</CopyText>}</Pressable><Row language={language} label={c.settings.voice} value={voice} setValue={updateVoice}/><CopyText language={language} style={styles.settingLabel}>{language === 'ur' ? 'رہنمائی پلانر' : 'Guidance planner'}</CopyText><Pressable style={styles.setting} onPress={() => updatePlanner('local')}><CopyText language={language}>{language === 'ur' ? 'مقامی اور نجی' : 'Local and private'}</CopyText>{planner === 'local' && <Text style={styles.active}>{c.settings.selected}</Text>}</Pressable><Pressable style={styles.setting} onPress={() => updatePlanner('gpt')}><Text>GPT-5.6</Text>{planner === 'gpt' && <Text style={styles.active}>{c.settings.selected}</Text>}</Pressable><CopyText language={language} style={styles.footnote}>{gptAvailable ? (language === 'ur' ? 'GPT پلانر محفوظ سرور سے جڑا ہوا ہے۔' : 'GPT planning is connected through the configured secure endpoint.') : (language === 'ur' ? 'GPT سیٹ اپ نہ ہو تو اسٹیپلی خودکار طور پر مقامی پلانر استعمال کرتا ہے۔' : 'If GPT is not configured, Stepli automatically uses the local planner.')}</CopyText><Row language={language} label={c.settings.textSize} value={large} setValue={setLarge}/></Screen>; }
function Row({label, value, setValue, language}: any) { return <View style={styles.setting}><CopyText language={language}>{label}</CopyText><Switch value={value} onValueChange={setValue} trackColor={{true: C.sage}}/></View>; }
export default function App() {
  const [language, setLanguageState] = useState<Language | null>(null); const [onboardingComplete, setOnboardingComplete] = useState(false); const [loaded, setLoaded] = useState(false);
  useEffect(() => { Promise.all([StepliOverlay.getLanguage(), StepliOverlay.getOnboardingComplete()]).then(([savedLanguage, complete]) => { setLanguageState(savedLanguage); setOnboardingComplete(complete); setLoaded(true); }).catch(() => setLoaded(true)); }, []);
  const setLanguage = async (value: Language) => { await StepliOverlay.setLanguage(value); setLanguageState(value); };
  const completeOnboarding = async () => { await StepliOverlay.setOnboardingComplete(); setOnboardingComplete(true); };
  if (!loaded) return <SafeAreaView style={styles.safe}/>;
  if (!language) return <LanguageScreen onChoose={setLanguage}/>;
  return <NavigationContainer><Stack.Navigator initialRouteName={onboardingComplete ? 'Home' : 'Permissions'} screenOptions={{headerShown: false, animation: 'fade'}}><Stack.Screen name="Permissions">{props => <Permissions {...props} language={language}/>}</Stack.Screen><Stack.Screen name="Onboarding">{props => <Onboarding {...props} language={language} completeOnboarding={completeOnboarding}/>}</Stack.Screen><Stack.Screen name="Home">{props => <Home {...props} language={language}/>}</Stack.Screen><Stack.Screen name="Settings">{props => <Settings {...props} language={language} setLanguage={setLanguage}/>}</Stack.Screen></Stack.Navigator></NavigationContainer>;
}
const styles = StyleSheet.create({safe:{flex:1,backgroundColor:C.cream},scroll:{flexGrow:1},screen:{flex:1,padding:28,backgroundColor:C.cream},heroLogo:{width:128,height:128,alignSelf:'center',marginTop:42,resizeMode:'contain'},eyebrow:{color:C.sage,fontWeight:'700',letterSpacing:1,textTransform:'uppercase',fontSize:13,marginTop:24},title:{fontFamily:'serif',fontSize:38,lineHeight:46,color:C.dark,marginTop:18,fontWeight:'700'},homeTitle:{fontFamily:'serif',fontSize:34,lineHeight:42,color:C.dark,marginTop:56,fontWeight:'700'},body:{fontSize:19,lineHeight:29,color:C.ink,marginTop:18},button:{minHeight:56,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:C.amber,marginTop:20,paddingHorizontal:20},buttonText:{color:'#fff',fontSize:18,fontWeight:'700'},secondary:{backgroundColor:'transparent',borderWidth:1,borderColor:C.sage},secondaryText:{color:C.dark},permissionStatus:{backgroundColor:C.pale,borderRadius:16,padding:18,gap:12,marginTop:32},guide:{backgroundColor:'#FFF0DF',borderRadius:16,padding:18,marginTop:18},guideTitle:{fontSize:17,fontWeight:'700',color:C.dark},guideBody:{fontSize:15,lineHeight:23,color:C.ink,marginTop:8},footnote:{fontSize:14,lineHeight:20,color:C.ink,marginTop:20},flex:{flex:1},topRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},brand:{flexDirection:'row',alignItems:'center',gap:8},headerLogo:{width:38,height:38,resizeMode:'contain'},logo:{fontFamily:'serif',fontWeight:'700',fontSize:28,color:C.dark},settings:{fontSize:16,color:C.sage,fontWeight:'700'},goalLabel:{fontSize:15,color:C.sage,fontWeight:'700',marginTop:28,marginBottom:8},goalInput:{minHeight:92,borderWidth:1,borderColor:C.sage,borderRadius:16,padding:15,fontSize:17,color:C.ink,textAlignVertical:'top',backgroundColor:'#F6F9F0'},activeGoal:{backgroundColor:'#F6F9F0',borderRadius:16,padding:17,marginTop:20},activeGoalTitle:{fontWeight:'700',fontSize:17,color:C.dark},activeGoalText:{fontSize:16,lineHeight:23,color:C.ink,marginTop:4},lastInstruction:{fontSize:15,lineHeight:22,color:C.ink,marginTop:12},taskCard:{backgroundColor:C.pale,borderRadius:22,padding:20,marginTop:28,flexDirection:'row',alignItems:'center',gap:14},cardIcon:{fontSize:36},cardTitle:{fontSize:21,fontWeight:'700',color:C.dark,lineHeight:27},cardBody:{fontSize:15,lineHeight:21,color:C.ink,marginTop:5},arrow:{fontSize:40,color:C.amber},settingLabel:{fontSize:15,color:C.sage,fontWeight:'700',marginTop:35,marginBottom:8},setting:{minHeight:61,borderBottomWidth:1,borderColor:'#D9DECF',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},active:{color:C.sage,fontWeight:'700'},rtl:{writingDirection:'rtl',textAlign:'right',fontFamily:'NotoSansArabic-Regular'}});
