export const en = {
  language: {headline: 'Choose your language', english: 'English', urdu: 'اردو'},
  permissions: {setup: 'Stepli setup', overlay: {headline: 'One thing I need first', body: 'So I can show you what to tap, right on your screen, I need permission to appear over other apps.', cta: 'Allow overlay'}, accessibility: {headline: 'One more thing', body: 'So I know which screen you’re on and can guide you correctly, I need accessibility access. I only look — I never tap anything for you.', cta: 'Open accessibility settings'}, overlayStatus: 'Appear over other apps', accessibilityStatus: 'Read-only screen guidance', checkCta: 'I’ve allowed it — check again', guideTitle: 'What to choose on the next page', guideBody: '1. Tap “Installed apps” or “Downloaded apps”.\n2. Choose “Stepli screen guidance”.\n3. Turn on “Use Stepli screen guidance”.\n4. Tap Allow.\n\nThis is read-only: Stepli can see Foodpanda’s screen to highlight the next step. It cannot tap, type, or place an order.', footnote: 'Stepli only reads the Foodpanda screen to show the next instruction. It never taps, types, or places an order for you.'},
  onboarding: {screen1: {headline: 'You’re not bad with technology.', body: 'You just haven’t had someone show you, one step at a time. That’s what Stepli is for.'}, screen2: {headline: 'I’ll never do it for you.', body: 'I just tell you what to tap next. You stay in control the whole time.'}, continue: 'Continue', begin: 'Let’s begin'},
  home: {greeting: 'Hi! What would you like to do today?', subtext: 'Tap below and I’ll walk you through it.', cardFoodpanda: 'Order food with Foodpanda', cardBody: 'I’ll stay beside you, one step at a time.', settings: 'Settings'},
  food: {
    locationStart: {text: 'Foodpanda may first ask for your location. Tap “Confirm location,” “Set location,” or “Choose location.” If you already see the home screen, tap “I am ready” below.', confirm: 'I am ready'},
    locationSearch: {text: 'Search for your area, street, or building. Choose the correct result, then add the address details Foodpanda asks for.', confirm: 'I added my location'},
    locationConfirm: {text: 'Check that the address is correct, then tap “Confirm location” or “Save address.”', confirm: 'I confirmed the address'},
    promo: {text: 'A promotion may appear. You can tap “Not now,” “Skip,” or the close button. If no promotion appears, continue below.', confirm: 'I am ready'},
    search: {text: 'Let’s find something to eat. Tap the search bar at the top.', confirm: 'I tapped it'},
    searchSubmit: {text: 'Type what you would like to eat. Then tap the magnifying-glass search icon.', confirm: 'I searched'},
    restaurant: {text: 'Tap a restaurant you like from the list.', confirm: 'I picked one'},
    addToCart: {text: 'Beside the dish you want, find the small + button. Tap it once to add the dish.', confirm: 'I added it'},
    viewCart: {text: 'At the bottom of the screen, tap “View your cart.”', confirm: 'I opened my cart'},
    cartReview: {text: 'Review your cart. Use + or − to change an item quantity if you need to, then tap “Checkout.”', confirm: 'I reviewed my cart'},
    addressReview: {text: 'On the checkout page, check the delivery address at the top. Tap “Change” if it is not the address you want.', confirm: 'My address is correct'},
    deliveryOption: {text: 'Choose the delivery option and price that suits you. Read the delivery fee before continuing.', confirm: 'I chose delivery'},
    paymentChange: {text: 'Find the payment method section. Tap “Change” if you want to use a different payment method.', confirm: 'I opened payment options'},
    paymentMethod: {text: 'Choose “Cash on delivery,” or add/select a card. Only continue when the payment method shown is the one you want.', confirm: 'I chose payment'},
    confirmAddress: {text: 'Check the address at the top once more. When everything is right, tap “Confirm address” or “Continue.”', confirm: 'I confirmed the address'},
    placeOrder: {text: 'If Foodpanda already shows that your order is complete, you are done. Otherwise, review the food, delivery price, address, and payment method, then tap “Place order” only when you are ready.', confirm: 'I finished this order'},
  },
  celebration: {headline: 'You did it! 🎉', body: 'You just did that all by yourself.', ctaAgain: 'Do it again', ctaHome: 'Back to home'}, error: {generic: 'No worries — let’s try that step again together.', notFound: 'Hmm, I don’t see that yet. Take a look at your screen.', retryCta: 'Show me again'}, settings: {title: 'Settings', language: 'Language', languageEnglish: 'English', languageUrdu: 'اردو', voice: 'Voice guidance', textSize: 'Text size', selected: 'Selected', step: 'Step'}, common: {stepOf: 'of', notInstalledTitle: 'Foodpanda isn’t installed', notInstalledBody: 'Please install Foodpanda first, then come back and try again.'},
};
