import {StyleSheet} from 'react-native';
import {C} from './colors';

export const styles = StyleSheet.create({
  safe: {flex: 1, backgroundColor: C.bg},
  boot: {flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10},
  scroll: {flexGrow: 1, paddingBottom: 20},
  screen: {flex: 1, paddingHorizontal: 16, paddingVertical: 12, backgroundColor: C.bg},
  heroLogo: {width: 72, height: 72, alignSelf: 'center', marginTop: 20, resizeMode: 'contain'},
  eyebrow: {color: C.sage, fontWeight: '700', letterSpacing: 0.6, textTransform: 'uppercase', fontSize: 11, marginTop: 10},
  title: {fontSize: 22, lineHeight: 28, color: C.dark, marginTop: 8, fontWeight: '700'},
  homeTitle: {fontSize: 20, lineHeight: 26, color: C.dark, marginTop: 12, marginBottom: 2, fontWeight: '700'},
  body: {fontSize: 13, lineHeight: 18, color: C.ink, marginTop: 6},
  button: {minHeight: 42, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: C.amber, marginTop: 10, paddingHorizontal: 14},
  buttonText: {color: '#fff', fontSize: 14, fontWeight: '700', textAlign: 'center'},
  secondary: {backgroundColor: C.white, borderWidth: 1, borderColor: C.line},
  secondaryText: {color: C.dark},
  danger: {backgroundColor: C.danger},
  dangerText: {color: '#fff'},
  disabled: {opacity: 0.55},
  permissionStatus: {backgroundColor: C.white, borderRadius: 10, padding: 12, gap: 6, marginTop: 12, borderWidth: 1, borderColor: C.line},
  guide: {backgroundColor: C.white, borderRadius: 10, padding: 12, marginTop: 10, borderWidth: 1, borderColor: C.line},
  guideTitle: {fontSize: 13, fontWeight: '700', color: C.dark},
  guideBody: {fontSize: 12, lineHeight: 17, color: C.ink, marginTop: 4},
  footnote: {fontSize: 11, lineHeight: 15, color: C.ink, marginTop: 8},
  hint: {fontSize: 12, lineHeight: 16, color: C.ink, marginTop: 6},
  flex: {flex: 1},
  topRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  topActions: {flexDirection: 'row', alignItems: 'center', gap: 12},
  menuButton: {minWidth: 32, minHeight: 32, alignItems: 'center', justifyContent: 'center'},
  menuIcon: {fontSize: 23, color: C.dark, lineHeight: 26},
  menuOverlay: {flex: 1, flexDirection: 'row-reverse'},
  menuBackdrop: {flex: 1, backgroundColor: 'rgba(24, 37, 25, 0.36)'},
  sideMenu: {width: '78%', maxWidth: 320, minHeight: '100%', backgroundColor: C.bg, paddingHorizontal: 16, paddingTop: 48, shadowColor: '#000', shadowOffset: {width: 2, height: 0}, shadowOpacity: 0.2, shadowRadius: 8, elevation: 8},
  sideMenuHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 18},
  menuClose: {fontSize: 28, lineHeight: 30, color: C.dark, paddingHorizontal: 6},
  menuItem: {minHeight: 52, borderBottomWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  brand: {flexDirection: 'row', alignItems: 'center', gap: 6},
  headerLogo: {width: 26, height: 26, resizeMode: 'contain'},
  logo: {fontWeight: '700', fontSize: 18, color: C.dark},
  settings: {fontSize: 13, color: C.sage, fontWeight: '600'},
  taskCard: {backgroundColor: C.white, borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12, marginTop: 8, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: C.line},
  addGuideCard: {backgroundColor: C.white, borderColor: C.sage, borderWidth: 1, borderStyle: 'dashed', borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12, marginTop: 10, flexDirection: 'row', alignItems: 'center', gap: 8},
  cardIcon: {fontSize: 20},
  addGuideIcon: {fontSize: 18, color: C.sage},
  cardTitle: {fontSize: 14, fontWeight: '700', color: C.dark, lineHeight: 18},
  cardBody: {fontSize: 12, lineHeight: 16, color: C.ink, marginTop: 2},
  cardMeta: {fontSize: 11, lineHeight: 14, color: C.sage, fontWeight: '600', marginTop: 2},
  arrow: {fontSize: 20, color: C.amber},
  settingLabel: {fontSize: 11, color: C.sage, fontWeight: '700', marginTop: 14, marginBottom: 2, textTransform: 'uppercase', letterSpacing: 0.4},
  setting: {minHeight: 44, borderBottomWidth: 1, borderColor: C.line, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  settingText: {fontSize: 14, color: C.dark},
  active: {color: C.sage, fontWeight: '700', fontSize: 12},
  rtl: {writingDirection: 'rtl', textAlign: 'right', fontFamily: 'NotoSansArabic-Regular'},
  sectionRow: {marginTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  sectionTitle: {fontSize: 13, fontWeight: '700', color: C.dark, marginTop: 12},
  link: {fontSize: 12, fontWeight: '700', color: C.sage, marginTop: 6},
  activeGuide: {backgroundColor: C.white, borderRadius: 10, padding: 10, marginTop: 8, borderWidth: 1, borderColor: C.line},
  activeGuideTitle: {fontWeight: '700', fontSize: 13, color: C.dark, lineHeight: 17},
  activeGuideText: {fontSize: 12, lineHeight: 16, color: C.ink, marginTop: 2},
  loader: {marginTop: 8},
  loaderRow: {flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10},
  loaderLabel: {fontSize: 12, color: C.ink},
  back: {alignSelf: 'flex-start', paddingVertical: 4, paddingRight: 10},
  backText: {fontSize: 13, fontWeight: '700', color: C.sage},
  screenHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 4, minHeight: 32},
  languageSwitch: {position: 'relative', alignItems: 'flex-end', zIndex: 10},
  languagePickerButton: {minHeight: 30, minWidth: 82, paddingHorizontal: 10, borderRadius: 8, borderWidth: 1, borderColor: C.line, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center'},
  languageMenu: {position: 'absolute', top: 34, right: 0, minWidth: 132, borderRadius: 9, overflow: 'hidden', borderWidth: 1, borderColor: C.line, backgroundColor: C.white, elevation: 5, shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 5, shadowOffset: {width: 0, height: 2}},
  languageOption: {minHeight: 40, justifyContent: 'center', paddingHorizontal: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line},
  languageChip: {
    minHeight: 28,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  languageChipActive: {borderColor: C.sage, backgroundColor: C.pale},
  languageChipText: {fontSize: 12, fontWeight: '600', color: C.ink},
  languageChipTextActive: {color: C.sage, fontWeight: '700'},
  notice: {backgroundColor: C.white, borderRadius: 10, padding: 12, marginTop: 8, borderWidth: 1, borderColor: C.line},
  noticeTitle: {fontSize: 13, fontWeight: '700', color: C.dark},
  noticeBody: {fontSize: 12, lineHeight: 16, color: C.ink},
  authCard: {backgroundColor: C.white, borderRadius: 12, padding: 12, marginTop: 10, borderWidth: 1, borderColor: C.line},
  input: {minHeight: 40, borderWidth: 1, borderColor: C.line, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, fontSize: 14, color: C.ink, backgroundColor: C.white, marginTop: 8},
  searchField: {minHeight: 42, borderWidth: 1, borderColor: C.line, borderRadius: 8, paddingHorizontal: 10, backgroundColor: C.pale, marginTop: 10, marginBottom: 6, flexDirection: 'row', alignItems: 'center', gap: 7},
  searchIcon: {fontSize: 24, lineHeight: 26, color: C.sage, fontWeight: '700'},
  searchInput: {flex: 1, minHeight: 40, paddingVertical: 8, fontSize: 14, color: C.ink},
  tabRow: {flexDirection: 'row', gap: 6, marginTop: 12, marginBottom: 4},
  tab: {flex: 1, minHeight: 38, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6, borderRadius: 9, borderWidth: 1, borderColor: C.line, backgroundColor: C.white},
  tabActive: {backgroundColor: C.sage, borderColor: C.sage},
  tabText: {fontSize: 12, color: C.ink, fontWeight: '700', textAlign: 'center'},
  tabTextActive: {color: C.white},
  multilineInput: {minHeight: 56, textAlignVertical: 'top'},
  signedIn: {backgroundColor: C.white, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 10, marginTop: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: C.line},
  signedInEmail: {flex: 1, fontSize: 12, lineHeight: 16, color: C.ink},
  guideListItem: {backgroundColor: C.white, borderRadius: 10, padding: 10, marginTop: 6, borderWidth: 1, borderColor: C.line},
  guidePageActions: {marginTop: 2},
  removeGuideButton: {alignSelf: 'flex-end', paddingHorizontal: 8, paddingVertical: 7},
  appPicker: {backgroundColor: C.white, borderRadius: 10, marginTop: 8, borderWidth: 1, borderColor: C.line, padding: 8, maxHeight: 260},
  appPickerList: {maxHeight: 190},
  appOption: {paddingVertical: 8, paddingHorizontal: 6, borderBottomWidth: 1, borderColor: C.line},
  appOptionLabel: {fontSize: 13, color: C.dark, fontWeight: '700'},
  appOptionPackage: {fontSize: 11, color: C.sage, marginTop: 2},
  stepEditor: {backgroundColor: C.white, borderRadius: 10, padding: 10, marginTop: 8, borderWidth: 1, borderColor: C.line},
  stepHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  stepTitle: {fontSize: 13, fontWeight: '700', color: C.dark},
  remove: {fontSize: 12, fontWeight: '700', color: C.danger},
  matcherLabel: {fontSize: 11, color: C.sage, fontWeight: '700', marginTop: 8},
  celebrate: {fontSize: 40, marginTop: 36, textAlign: 'center'},
  appGroup: {backgroundColor: C.white, borderRadius: 12, marginTop: 8, borderWidth: 1, borderColor: C.line, overflow: 'hidden'},
  appGroupHeader: {flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, paddingHorizontal: 12},
  appGroupBody: {borderTopWidth: 1, borderTopColor: C.line, paddingBottom: 4},
  appGroupGuide: {
    minHeight: 44,
    paddingVertical: 10,
    paddingHorizontal: 12,
    paddingLeft: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.line,
  },
  appGroupGuideLast: {borderBottomWidth: 0},
  chevron: {fontSize: 14, color: C.sage, fontWeight: '700'},
  guideDialog: {
    backgroundColor: C.cream,
    borderRadius: 18,
    padding: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: C.line,
  },
  guideDialogHeader: {flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8},
  guideDialogAvatar: {width: 48, height: 48, resizeMode: 'contain'},
  guideDialogProgress: {fontSize: 13, fontWeight: '700', color: C.sage},
  guideDialogTitle: {fontSize: 18, lineHeight: 24, fontWeight: '700', color: C.dark, marginTop: 4},
  guideDialogBody: {fontSize: 14, lineHeight: 20, color: C.ink, marginTop: 6, marginBottom: 4},
  guideCardImage: {width: 44, height: 44, resizeMode: 'contain'},
});
